apiVersion: v1
kind: Service
metadata:
  name: nfs-server-service
  labels:
    service_name: nfs-server
    service_type: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    service_name: nfs-server
  type: ClusterIP
