apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-jenkins-storage-pv
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server-service.jenkins.svc.cluster.local
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: premium-rwo
  resources:
    requests:
      storage: "300Gi"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-jenkins-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 300Gi
