---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  namespace: jenkins
  name: jenkins-service-account-token-secret
  labels:
    service_name: jenkins
    service_type: jenkins
  annotations:
    kubernetes.io/service-account.name: jenkins-service-account
