apiVersion: v1
data:
  policy.csv: |
    g, johanes.steven@istock.co.id, role:admin
    g, admin role:admin

    p, role:developer, applications, get, */*, allow

    g, andrew.budiman@istock.co.id, role:developer

  scopes: '[cognito:groups, email]'
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
