---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-service-account
  annotations:
    iam.gke.io/gcp-service-account: $(service_account)
  labels:
    service_name: jenkins
    service_type: jenkins
