---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
  labels:
    service_name: jenkins
    service_type: jenkins
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: premium-rwo
  resources:
    requests:
      storage: "150Gi"
