---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-svc
  labels:
    service_name: jenkins
    service_type: jenkins
  annotations:
    cloud.google.com/load-balancer-type: Internal
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080

  selector:
    service_name: jenkins
  type: LoadBalancer
