apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    service_name: jenkins
    service_type: jenkins
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service_name: jenkins
  template:
    metadata:
      labels:
        service_name: jenkins
        service_type: jenkins
    spec:
      securityContext:
        runAsUser: 0
      serviceAccountName: "jenkins-service-account"
      initContainers:
        - name: "copy-default-config"
          image: "jenkins/jenkins:2.346.2"
          imagePullPolicy: "Always"
          command: [ "sh", "/var/jenkins_config/apply_config.sh" ]
          env:
            - name: CASC_JENKINS_CONFIG
              value: "/var/jenkins_home/casc_configs"
            - name: SECRETS
              value: "/usr/share/jenkins/ref/secrets/"
            - name: CACHE_DIR
              value: "/var/jenkins_home/caches"
            - name: JENKINS_UC_DOWNLOAD
              value: "https://mirrors.huaweicloud.com/jenkins/"
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/jenkins_home
              name: jenkins-home
            - mountPath: /var/jenkins_config
              name: jenkins-config
            - mountPath: /usr/share/jenkins/ref/plugins
              name: plugins
            - mountPath: /var/jenkins_plugins
              name: plugin-dir
      containers:
        - name: jenkins
          image: "jenkins/jenkins:2.346.2"
          imagePullPolicy: "Always"
          args: [ "--httpPort=8080"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JAVA_OPTS
              value: >
                -Djenkins.install.runSetupWizard=false
                -Duser.timezone=Asia/Jakarta
                -Dcasc.reload.token="ajaibajaibajaib"
            - name: JENKINS_OPTS
              value: ""
            - name: JENKINS_SLAVE_AGENT_PORT
              value: "50000"
            - name: CASC_JENKINS_CONFIG
              value: "/var/jenkins_home/casc_configs"
            - name: SECRETS
              value: "/usr/share/jenkins/ref/secrets/"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 50000
              name: slavelistener
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 10
          resources:
            limits:
              cpu: 2000m
              memory: 4096Mi
            requests:
              cpu: 1000m
              memory: 3072Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/jenkins_home
              name: jenkins-home
              readOnly: false
            - mountPath: /var/jenkins_home/casc_configs
              name: jenkins-casc
            - mountPath: /var/jenkins_home/casc_configs/config_file_provider
              name: jenkins-casc-config-file-provider
              readOnly: true
            - mountPath: /var/jenkins_config
              name: jenkins-config
              readOnly: true
            - mountPath: /usr/share/jenkins/ref/secrets/
              name: secrets-dir
              readOnly: true
            - mountPath: /usr/share/jenkins/ref/plugins/
              name: plugin-dir
              readOnly: false
      volumes:
      - name: plugins
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: jenkins-config
        configMap:
          name: jenkins-config
      - name: secrets-dir
        secret:
          secretName: jenkins-casc-secret #pragma: allowlist secret
      - name: plugin-dir
        emptyDir: {}
      - name: jenkins-casc
        configMap:
          name: jenkins-casc-config
      - name: jenkins-casc-config-file-provider
        configMap:
          name: jenkins-casc-config-file-provider
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
