---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent-svc
  labels:
    service_name: jenkins
    service_type: jenkins
spec:
  ports:
    - port: 50000
      targetPort: 50000

      name: slavelistener
  selector:
    service_name: jenkins
  type: ClusterIP
